[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tic-tac-toe"
version = "0.0.1"
authors = [
    { name = "Tim Pogue", email = "t.pogue.python@gmail.com" },
]

[project.urls]
Homepage = "https://github.com/Accoustium/tictactoe_python"

[tool.black]
line-length = 88
target-version = ['py37', 'py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''
